apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-runner
    image: alpine:3.14
    command: ['sh', '-c', 'sleep infinity']
    securityContext:
      privileged: true
    resources:
      limits:
        google.com/tpu: 4
      requests:
        google.com/tpu: 4
  - name: test-docker
    image: alpine:3.14
    command: ['sh', '-c', 'sleep infinity']
  nodeSelector:
    cloud.google.com/gke-tpu-accelerator: tpu-v4-podslice
    cloud.google.com/gke-tpu-topology: 2x2x1
