replicaCount: 3
concurrency: 24
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 400m
    memory: 64Mi
caCertValidityDuration: 24h
certRotationCheckFrequency: 30m
image:
  tag: v0.16.0-rc.3
runner:
  image:
    tag: v0.16.0-rc.3
  grpc:
    maxMessageSize: 30
extraEnv:
  - name: TF_LOG
    value: debug
