replicaCount: 3
concurrency: 24
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 400m
    memory: 64Mi
caCertValidityDuration: 24h
certRotationCheckFrequency: 30m
image:
  tag: v0.16.0-rc.2
runner:
  image:
    tag: v0.16.0-rc.2
  grpc:
    maxMessageSize: 30
branchPlanner:
  enabled: true
  image:
    tag: v0.16.0-rc.2
