name: TPU Test
run-name: ${{ github.actor }} is testing self-hosted runners on TPUs
on: [push]
jobs:
  tpu-test:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip3 install torch~=2.0.0 https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-2.0-cp38-cp38-linux_x86_64.whl
      - run: pip3 install expecttest numpy pyyaml torch_xla[tpuvm]
      - run: pwd
      - run: python3 test/test_operations.py -v
