name: TPU Test
run-name: ${{ github.actor }} is testing self-hosted runners on TPUs
on: [push]
jobs:
  tpu-test:
    runs-on: runner-set
    steps:
      - run: |
          sudo apt-get upgrade -y
          sudo apt-get install -y git-all
          git clone --recursive https://github.com/pytorch/pytorch
          cd pytorch/
          python3 setup.py install
          git clone --recursive https://github.com/pytorch/xla.git
          cd xla/
          python3 setup.py install
