name: TPU Test
run-name: ${{ github.actor }} is testing self-hosted runners on TPUs
on: [push]
jobs:
  tpu-test:
    runs-on: runner-set
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install git-all -y
          LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/runner/_work/_tool/Python/3.8.18/x64/lib 
          pip3 install ansible
          git clone --recursive https://github.com/pytorch/pytorch
          cd pytorch/
          pwd
          git clone --recursive https://github.com/pytorch/xla.git
          cd xla/infra/ansible
          pwd
          echo $LD_LIBRARY_PATH
          echo $AGENT_TOOLSDIRECTORY
          echo $RUNNER_TOOL_CACHE
          sudo ansible-playbook playbook.yaml -e "stage=build arch=amd64 accelerator=tpu" --tags "bazel,configure_env,install_deps"
          cd ../../..
          pwd
          python3 setup.py install
          cd xla/
          python3 setup.py install
