name: TPU Test
run-name: ${{ github.actor }} is testing self-hosted runners on TPUs
on: [push]
jobs:
  tpu-test:
    runs-on: runner-set
    steps:
      - env:
          PJRT_DEVICE: TPU
          BUNDLE_LIBTPU: 0
          TPUVM_MODE: 0
        run: |
          sudo apt-get upgrade -y
          sudo apt-get update -y
          git clone --recursive https://github.com/pytorch/pytorch
          cd pytorch/
          sudo python3 setup.py install
          git clone --recursive https://github.com/pytorch/xla.git
          cd xla/
          sudo python3 setup.py install
      - env:
          PJRT_DEVICE: TPU
        run: |
          pwd
          ls -al
          cd pytorch/xla
          python3 test/test_operations.py -v
